#!/bin/bash

# Set any environment variables here
# These are inherited by all processes, *except* RStudio
export EDITOR=nano

# Tell gh-scoped-creds which GitHub app to use for push access
# See https://github.com/jupyterhub/gh-scoped-creds#github-app-configuration
export GH_SCOPED_CREDS_CLIENT_ID
export GH_SCOPED_CREDS_APP_URL

exec "$@"
